# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: chaleanoh
description: > # this means to ignore newlines until "baseurl:"
  On the off chance that you wanted to learn how to pronounce "Chellino," now 
  you know. And you can also look through Nicole M. Chellino's professional portfolio. 
  Here are a few of my projects, creativity, and hopefully a dash of professionalism - hopefully.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chaleanoh.com" # the base hostname & protocol for your site
twitter_username: jekyllrb

# Build settings
markdown: kramdown
